Repository ksercs/GitCherry, pull requests merged in 2021-04, with the labels that each got.

#10 Migration from orgstruct
  dxcherry/.env.example
  dxcherry/package.json
  dxcherry/src/reviewers/config.ts
  dxcherry/src/reviewers/orgstruct.ts
  dxcherry/src/reviewers/payload.ts
  dxcherry/src/reviewers/reviewer.ts
Labels: backend, refactoring

#12 Tribe bug fix
  dxcherry/package.json
  dxcherry/src/reviewers/payload.ts
  dxcherry/src/reviewers/reviewer.ts
Labels: backend, bug

#13 Improve pull request opening UX
  dxcherry/src/git/client.ts
  dxcherry/src/git/constants.ts
  dxcherry/src/github/client.ts
  dxcherry/src/github/createPullRequest.ts
  dxcherry/src/info/Logger.ts
  dxcherry/src/processCherryPickRequest.ts
  dxcherry/src/tree/payload.ts
Labels: feature
